[project]
name = "binance-merchant-trading-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pip>=25.2",
    "psycopg2>=2.9.10",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.43",
]
