[project]
name = "binance-merchant-trading-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "binance-sdk-c2c>=1.7.0",
    "ipykernel>=7.0.0",
    "pip>=25.2",
    "setuptools>=80.9.0",
]
